/**
 * /vincular [código]
 *
 * Links a Discord user to an editor account using a one-time token
 * generated by Joaco in the web app.
 */

import type { DiscordInteraction } from "../types";
import { getUser, getOption } from "../types";
import { reply, replyError } from "../respond";
import { notifyEditorLinked } from "../notify";
import { createBotClient } from "@/lib/supabase/bot";

export async function handleVincular(
  interaction: DiscordInteraction
): Promise<Response> {
  const user = getUser(interaction);
  if (!user) return replyError("No se pudo identificar tu usuario de Discord.");

  const token = getOption(interaction, "código")?.toUpperCase().trim();
  if (!token) return replyError("Tenés que ingresar un código.");

  const supabase = createBotClient();

  // Check if already linked
  const { data: existing } = await supabase
    .from("editors")
    .select("id, name")
    .eq("discord_id", user.id)
    .maybeSingle();

  if (existing) {
    return reply(
      `✅ Ya estás vinculado como **${existing.name}**.\n` +
        `Si necesitás cambiar la vinculación, pedile a Joaco que regenere tu código.`
    );
  }

  // Find the editor with this token
  const { data: editor, error: findErr } = await supabase
    .from("editors")
    .select("id, name")
    .eq("discord_link_token", token)
    .maybeSingle();

  if (findErr || !editor) {
    return replyError(
      "Código inválido o ya fue usado. Pedile a Joaco que genere uno nuevo."
    );
  }

  // Link: set discord_id, clear token
  const { error: updateErr } = await supabase
    .from("editors")
    .update({ discord_id: user.id, discord_link_token: null })
    .eq("id", editor.id);

  if (updateErr) {
    console.error("[discord:vincular] update error:", updateErr);
    return replyError("Hubo un error al vincular. Intentá de nuevo.");
  }

  // Notify Joaco (awaited — serverless terminates on return)
  await notifyEditorLinked({
    editorName: editor.name,
    discordUsername: user.global_name ?? user.username,
  });

  return reply(
    `✅ ¡Listo, **${editor.name}**! Tu cuenta de Discord ya está vinculada.\n` +
      `Ahora podés usar \`/proyectos\`, \`/estado\` y \`/mover\`.`
  );
}
